// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var colors = map[string]string{
	"B": "black",
	"U": "blue",
	"G": "green",
	"R": "red",
	"W": "white",
}

func SearchForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-ext=\"submitjson\" hx-target=\"#output\" hx-post=\"/api/search\"><div class=\"grid search-form\"><fieldset role=\"search\" style=\"grid-column: 1/9\"><input type=\"search\" name=\"name\" placeholder=\"Search\"> <button type=\"submit\">Search</button></fieldset><div class=\"page-size-selector\"><label for=\"pageSize\">Page Size</label> <select name=\"pageSize\"><option value=\"10\">10</option> <option value=\"20\">20</option> <option value=\"30\">30</option> <option value=\"40\">40</option></select></div></div></form><!-- <div class=\"search-results\">\n        <article>\n            <img src=\"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=654951&type=card\" style=\"width: 80px; height: auto\" />\n        </article>\n    </div> --><button class=\"outline\" onclick=\"openModal()\">Advance search</button> <dialog class=\"advance-search\"><form hx-ext=\"submitjson\" hx-target=\"#output\" hx-post=\"/api/search\"><div class=\"grid search-form\"><fieldset role=\"search\" style=\"grid-column: 1/7\"><input type=\"search\" name=\"name\" placeholder=\"Search\"></fieldset><div class=\"grid-column: 8/9\"><label for=\"pageSize\">Page Size</label> <select name=\"pageSize\"><option value=\"10\">10</option> <option value=\"20\">20</option> <option value=\"30\">30</option> <option value=\"40\">40</option></select></div></div><fieldset role=\"group\"><legend>Color search</legend><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for k, v := range colors {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input type=\"checkbox\" name=\"color_value\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(k)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/search-form.templ`, Line: 55, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"> <label for=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(k)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/search-form.templ`, Line: 56, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(v)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/search-form.templ`, Line: 56, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div><input type=\"radio\" name=\"color_operand\" value=\"and\"> <label for=\"and\">AND</label> <input type=\"radio\" name=\"color_operand\" value=\"or\"> <label for=\"or\">OR</label></div></fieldset><button>Submit</button></form></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
