on: [push]

name: Build and Deploy

permissions:
  id-token: write

jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - name: Run script
              run: |
                echo "Hello, World!"
                docker run hello-world
              shell: bash
            # - name: login
            #   uses: azure/login@v2
            #   with:
            #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
            #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            # - name: Azure CLI script
            #   uses: azure/cli@v2
            #   with:
            #     azcliversion: latest
            #     inlineScript: |
            #         az account show