on:
  push:
    tags:
      - '*'

name: Build and Deploy

jobs:
    build-and-deploy:
        runs-on: self-hosted
        env:
            DOCKER_USER: ${{ vars.DOCKER_USER }}
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Build application
            
            run: |
              echo "Building application..."
              chmod +x ./scripts/build-app.sh
              ./scripts/build-app.sh 
              echo "Build complete."
            shell: bash
          - name: Deploy application
            run: |
              echo "Deploying application..."
              docker-compose up -d
              echo "Deployment complete."
            shell: bash