on:
  push:
    branches:
      - master

jobs:
  tag-image:
    runs-on: self-hosted
    env:
      DOCKER_USER: ${{ vars.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tag image
        run: |
          echo "Tagging image..."
          chmod +x ./scripts/tag-image.sh
          ./scripts/tag-image.sh
          echo "Tagging complete."
        shell: bash