on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-image:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tag image
        uses: anotherNick/github-tag-action@v1.70.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true